// src/config.js
const CONFIG = {
    GALAXY_COUNT: 100,
    FILAMENT_LINKS_MAX_DIST: 400,
    FORWARD_SPEED: 4.50,
    DEPTH_NEAR: 20,
    DEPTH_FAR: 1500,
    PROJECTION: 900,
    DARK_MATTER_COUNT: 300,
    MAX_ACTIVE_EXPLOSIONS: 12,
    EDGE_ON_CHANCE: 0.50,
    STAR_DUST_COUNT: 800,
    STAR_DUST_ATTRACTION_RADIUS: 260,
    STAR_DUST_CAPTURE_RADIUS: 48,
    STAR_DUST_BASE_SPEED: 0.50,
    STAR_DUST_PULL: 0.024,
    STAR_DUST_DARKMATTER_RADIUS: 260
};

export default CONFIG;